# Generated by Django 4.1 on 2025-10-09 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('gender', models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка')], max_length=1, verbose_name='Пол')),
                ('age', models.CharField(choices=[('kitten', 'Котенок (до 1 года)'), ('young', 'Молодой (1-3 года)'), ('adult', 'Взрослый (3-8 лет)'), ('senior', 'Пожилой (8+ лет)')], max_length=10, verbose_name='Возраст')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('description', models.TextField(verbose_name='Описание')),
                ('story', models.TextField(blank=True, verbose_name='История')),
                ('temperament', models.CharField(choices=[('active', 'Активный'), ('calm', 'Спокойный'), ('playful', 'Игривый'), ('affectionate', 'Ласковый'), ('shy', 'Стеснительный'), ('lazy', 'Ленивый')], max_length=20, verbose_name='Характер')),
                ('good_with_children', models.BooleanField(default=False, verbose_name='Ладит с детьми')),
                ('good_with_other_animals', models.BooleanField(default=False, verbose_name='Ладит с животными')),
                ('health_status', models.TextField(default='Здоров, привит, обработан от паразитов', verbose_name='Состояние здоровья')),
                ('special_needs', models.TextField(blank=True, verbose_name='Особые потребности')),
                ('vaccinated', models.BooleanField(default=True, verbose_name='Привит')),
                ('sterilized', models.BooleanField(default=True, verbose_name='Стерилизован')),
                ('status', models.CharField(choices=[('available', 'Ищет дом'), ('reserved', 'В процессе'), ('adopted', 'Пристроен')], default='available', max_length=10, verbose_name='Статус')),
                ('arrival_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата поступления')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Котик',
                'verbose_name_plural': 'Котики',
                'ordering': ['status', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Контактное сообщение',
                'verbose_name_plural': 'Контактные сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('manager', 'Менеджер'), ('barista', 'Бариста'), ('cat_carer', 'Заботник о котах'), ('cleaner', 'Уборщик'), ('volunteer', 'Волонтер'), ('vet', 'Ветеринар')], max_length=20, verbose_name='Должность')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('years_of_work', models.PositiveIntegerField(default=0, verbose_name='Опыт работы (лет)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный сотрудник')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['position', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('review', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Одобрен')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.staff', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Отзыв о сотруднике',
                'verbose_name_plural': 'Отзывы о сотрудниках',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('vegetarian', models.CharField(choices=[('none', 'Содержит животные продукты'), ('vegetarian', 'Вегетарианское'), ('vegan', 'Веганское')], default='none', max_length=20, verbose_name='Тип питания')),
                ('allergens', models.CharField(blank=True, max_length=200, verbose_name='Аллергены')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='Объем/Вес')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.menucategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Позиция меню',
                'verbose_name_plural': 'Позиции меню',
                'ordering': ['category', 'name'],
            },
        ),
    ]
