# Generated by Django 4.1 on 2025-10-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', 'Кофе и напитки'), ('tea', 'Чайная карта'), ('desserts', 'Десерты'), ('snacks', 'Закуски и сэндвичи'), ('cats', 'Лакомства для котиков'), ('specials', 'Специальные предложения')], max_length=100, verbose_name='Название категории'),
        ),
        migrations.DeleteModel(
            name='MenuCategory',
        ),
    ]
