# Generated by Django 4.1 on 2025-10-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_menuitem_category_delete_menucategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок в категории'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('coffee', '☕ Кофе и напитки'), ('tea', '🍵 Чайная карта'), ('desserts', '🍰 Десерты'), ('snacks', '🥪 Закуски и сэндвичи'), ('cats', '🐱 Лакомства для котиков'), ('specials', '⭐ Специальные предложения')], max_length=100, verbose_name='Категория'),
        ),
    ]
