# Generated by Django 4.1 on 2025-10-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_menuitem_options_menuitem_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.RemoveField(
            model_name='staff',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='years_of_work',
        ),
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='staff',
            name='name',
            field=models.CharField(default='Саша', max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='staff',
            name='surname',
            field=models.CharField(default='Кумко', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='static/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('barista', 'Бариста'), ('cat_caretaker', 'Смотритель за котиками'), ('cleaner', 'Уборщик')], max_length=20, verbose_name='Должность'),
        ),
    ]
