# Generated by Django 4.1 on 2025-10-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_staff_options_remove_staff_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='photo',
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('barista', 'Бариста'), ('cat_caretaker', 'Грумер'), ('vet', 'Ветеринар'), ('shef', 'Шеф Повар'), ('vet', 'Ветеринар')], max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
    ]
