# Generated by Django 4.1 on 2025-10-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_remove_staff_photo_staff_image_alter_cat_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Позиция меню', 'verbose_name_plural': 'Позиции меню'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.ImageField(upload_to='cats/static/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/static/images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cats/static/images/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('barista', 'Бариста'), ('cat_caretaker', 'Грумер'), ('vet', 'Ветеринар'), ('shef', 'Шеф Повар'), ('waiter', 'Официант')], max_length=20, verbose_name='Должность'),
        ),
    ]
